receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
  snmptrap: # this line represents the ID of your receiver

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  otlp/jaeger:
    endpoint: localhost:14317
    tls:
      insecure: true

service:
  pipelines:
    logs:
      receivers: [otlp, snmptrap]
      processors: [batch]
      exporters: [otlp/jaeger, debug]

  telemetry:
    logs:
      level: debug

